### ISSUE TITLE
[接口失效]: 知乎源抓取失败（源用户发布图片）

### ISSUE THREAD

**Issue by YanDao0313** [zkeq/news#12]
### 部署平台

vercel

### 您遇到的问题？

知乎用户“每天60秒读懂世界”于今日发布的文本版日报未过审，于晚上七点左右发布了图片版本的日报，这导致接口抓取失败，并带来了与日期相关的bug

### 接口失效？

知乎源

### 准备提交

- [X] 哦，天哪，这确实是一个bug。

**Comment by zkeq** [comment]
问题收到 我看下
